# Generated by Django 2.2.24 on 2025-01-15 12:27
from django.db import migrations

def automatize_construction_years(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Flat.objects.filter(construction_year__lt=2015).update(new_building = False)
    Flat.objects.filter(construction_year__gte=2015).update(new_building = True)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [migrations.RunPython(automatize_construction_years)
    ]
