# Generated by Django 2.2.24 on 2025-01-15 18:22
from itertools import chain
from django.db import migrations

def transfer_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat_set = Flat.objects.all()
    flat_iterator = flat_set.iterator()
    try: 
         first_flat = next(flat_iterator)
    except StopIteration:
         pass
    else:
        for flat in chain([first_flat], flat_iterator):
            Owner.objects.get_or_create(owner_name=flat.owner, owners_phonenumber=flat.owners_phonenumber, 
                                        defaults={'owner_pure_phone': flat.owner_pure_phone})


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [migrations.RunPython(transfer_owner_data)
    ]
